config/routes.rb
Rails.application.routes.draw do

  resources :blogs do
  resources :comments
  end
  get 'relationships/create'
  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show, :index]

  resources :resolutions do
        resources :tasks
      end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
      post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
    end
  authenticated :user do
    root 'blogs#index', as: :authenticated_root
  end

  unauthenticated do
    root 'home#home', as: :unauthenticated_root
  end
  namespace :admin do
    resources :users
  end




root to: 'home#home'
resources :relationships, only: [:create, :destroy]
resources :tasks

resources :conversations do
  resources :messages
end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
has_many :comments, dependent: :destroy
belongs_to :user
validates :title, presence: true
validates :content, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @q = Blog.ransack(params[:q])
    @blogs=@q.result
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  @comments = @blog.comments
  @comment = @blog.comments.build
end


  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)
@blog.user_id = current_user.id
    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:resolution_id, :title, :content)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<div class="container-fluid">

<h1>Tracking!!!</h1><br><br>

<%= search_form_for @q do |f| %>
  <%= f.label :title_cont, 'Title' %>
  <%= f.search_field :title_cont %>
  <%= f.submit %>
<% end %>

<div class="table">


  <tbody>
    <% @blogs.each do |blog| %>

        <h2><%= blog.title %></h2><br>
        <h4><%= blog.content %></h4><br>
        <td><%= link_to 'Show', blog %></td><br><br><br>

        <% if current_user.id == blog.user_id %>

        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td><br><br>
<% end %>
    <% end %>
  </tbody>
</div>
</div>
<br>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="blog-text">
    <p><strong>Title</strong>：<%= @blog.title %></p>
    <p><strong>Content</strong>：<%= @blog.content %></p>
  </div>
  <p>List of comments (the contents below from here are important)</p>
  <!-- Get the HTML id of this comments_area and update only that part of the div-->
  <div id="comments_area">
    <!-- Render to display a list of posted comments on the blog details page -->
    <%= render partial: 'comments/index', locals: { comments: @comments, blog: @blog } %>
  </div>
  <!-- Render to display the comment input field on the detail page of the blog -->
  <%= render partial: 'comments/form', locals: { comment: @comment, blog: @blog } %>
  <%= link_to 'Edit', edit_blog_path(@blog) %> |
  <%= link_to 'Return', blogs_path %>
</div>