config/routes.rb
Rails.application.routes.draw do

  resources :blogs do
  resources :comments
  end
  get 'relationships/create'
  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show, :index]

  resources :resolutions do
        resources :tasks
      end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
      post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
    end
  authenticated :user do
    root 'blogs#index', as: :authenticated_root
  end

  unauthenticated do
    root 'home#home', as: :unauthenticated_root
  end
  namespace :admin do
    resources :users
  end




root to: 'home#home'
resources :relationships, only: [:create, :destroy]
resources :tasks

resources :conversations do
  resources :messages
end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/task.rb
class Task < ApplicationRecord
belongs_to :resolution
validates :task_title, presence: true
validates :task_details, presence: true
validates :frequency, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_resolution
    before_action :set_task, only: %i[ show edit update destroy ]

    # GET /tasks or /tasks.json
    def index
      @tasks = @resolution.tasks
    end

    # GET /tasks/1 or /tasks/1.json
    def show
    end

    # GET /tasks/new
    def new
      @task = @resolution.tasks.build
    end

    # GET /tasks/1/edit
    def edit
    end

    # POST /tasks or /tasks.json
    def create
      @task = @resolution.tasks.build(task_params)

      respond_to do |format|
        if @task.save
          format.html { redirect_to resolution_tasks_url(@resolution), notice: "task was successfully created." }
          format.json { render :show, status: :created, location: @task }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /tasks/1 or /tasks/1.json
    def update
      respond_to do |format|
        if @task.update(task_params)
          format.html { redirect_to resolution_tasks_url(@resolution), notice: "task was successfully updated." }
              format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end
    def completed_task
        @task = find_task
        if @task.task_completed_today?(date_today)
          flash[:message] = "You have already completed this resolution today!"
          redirect_to resolution_task_path(@resolution.task, @resolution)
        else
          @task.complete_task_today
          redirect_to resolution_task_path(@resolution.tasks, @resolution)
        end
      end
    # DELETE /tasks/1 or /tasks/1.json
    def destroy
      @task.destroy
      respond_to do |format|
        format.html { redirect_to resolution_tasks_url(@resolution), notice: "Task was successfully destroyed." }
        format.json { head :no_content }
      end
    end
end
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_task
        @task = @resolution.tasks.find(params[:id])
      end

      def date_today
          Time.now.localtime.to_date
        end
        def find_task
            Task.find(params[:id])
          end

      def get_resolution
        @resolution=Resolution.find(params[:resolution_id])
      end
      # Only allow a list of trusted parameters through.
      def task_params
        params.require(:task).permit(:task_title, :task_details, :frequency)
      end

app/helpers/tasks_helper.rb
module TasksHelper
  def days_until_end(task)
      (@resolution.end_date.to_date - Time.now.localtime.to_date).to_i
    end
end

app/views/tasks/_form.html.erb
<%= form_with(model: [@resolution, task], local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task_title %>
    <%= form.text_field :task_title %>
  </div>

  <div class="field">
    <%= form.label :task_details %>
    <%= form.text_field :task_details %>
  </div>

  <div class="field">
    <%= form.label :frequency %>
  <%= form.select :frequency, ['Weekly','Daily','Monthly'], {include_blank: 'Select Box'} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @resolution %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="container-fluid">
<h1>Tasks</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Task title</th>
      <th>Task details</th>
      <th>Frequency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.task_title %></td>
        <td><%= task.task_details %></td>
        <td><%= task.frequency %></td>
        <td><%= link_to 'Show resolution', [@resolution] %></td>
          <td><%= link_to 'View Tasks', resolution_task_url(@resolution, task) %></td>
      <td><%= link_to 'Edit task', edit_resolution_task_url(@resolution, task) %></td>
      <td><%= link_to 'Destroy task', [@resolution, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Task', new_resolution_task_path(@resolution) %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', resolution_tasks_path(@resolution)%>

app/views/tasks/show.html.erb
<p>
  <strong>Task title:</strong>
  <%= @task.task_title %>
</p>

<p>
  <strong>Task details:</strong>
  <%= @task.task_details %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @task.frequency %>
</p>




<%= link_to 'Edit', edit_resolution_task_path(@task) %> |
<%= link_to 'Back', resolution_tasks_path %>