config/routes.rb
Rails.application.routes.draw do

  resources :blogs do
  resources :comments
  end
  get 'relationships/create'
  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show, :index]

  resources :resolutions do
        resources :tasks
      end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
      post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
    end
  authenticated :user do
    root 'blogs#index', as: :authenticated_root
  end

  unauthenticated do
    root 'home#home', as: :unauthenticated_root
  end
  namespace :admin do
    resources :users
  end




root to: 'home#home'
resources :relationships, only: [:create, :destroy]
resources :tasks

resources :conversations do
  resources :messages
end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
     if user.try(:admin?)
       can :access, :rails_admin
       can :manage, :all

       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
has_many :comments, dependent: :destroy
belongs_to :user
validates :title, presence: true
validates :content, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
    validates :content, presence: true

end

app/models/completion_date.rb
class CompletionDate < ApplicationRecord
belongs_to :task
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
    belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
    # One conversation is one-to-many with many messages.
    has_many :messages, dependent: :destroy
    # [:sender_id, Set Validation to prevent: recipient_id] from being saved in the same combination.
    validates_uniqueness_of :sender_id, scope: :recipient_id
    # Explained below
    scope :between, -> (sender_id,recipient_id) do
      where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
    end
    # Explained below
    def target_user(current_user)
      if sender_id == current_user.id
        User.find(recipient_id)
      elsif recipient_id == current_user.id
        User.find(sender_id)
      end
    end
  end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
belongs_to :followed, class_name: "User"
belongs_to :follower, class_name: "User"
end

app/models/resolution.rb
class Resolution < ApplicationRecord
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true
has_many :blogs
belongs_to :user
validates :title, presence: true

validates :details, presence: true
validates :end_date, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
belongs_to :resolution
validates :task_title, presence: true
validates :task_details, presence: true
validates :frequency, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :resolutions
has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
has_many :following, through: :active_relationships, source: :followed
has_many :followers, through: :passive_relationships, source: :follower
has_many :blogs
def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = 'guests'
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def self.admin_guest
    find_or_create_by!(email: 'admin_guest@example.com') do |user|
      user.name = 'Guest administrator'
      user.password = SecureRandom.urlsafe_base64
      user.admin = 'true'
    end
  end 

def follow!(other_user)
  active_relationships.create!(followed_id: other_user.id)
end
#See if you follow
def following?(other_user)
  active_relationships.find_by(followed_id: other_user.id)
end
def unfollow!(other_user)
  active_relationships.find_by(followed_id: other_user.id).destroy
end
end

app/helpers/admin_helper.rb
module AdminHelper
  def admin?
        user_signed_in? && current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def admin?
  #         user_signed_in? && current_user.admin?
  #     end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/resolutions_helper.rb
module ResolutionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def days_until_end(task)
      (@resolution.end_date.to_date - Time.now.localtime.to_date).to_i
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myreso</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/08e12fc6fb.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
<div class='main-header'>
 <% if user_signed_in? %>
<li class='right'> <%= link_to "Admin Panel", rails_admin_path if admin? %>
      <li class='right'> <%= link_to "Resolutions", resolutions_path %></li>
      <li class='right'> <%= link_to "Blogs", blogs_path %></li>
       <li class='left'><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
     <% else %>
         <li class='left'><%= link_to "Sign up", new_user_registration_path %></li>
       <li class='right'> <%= link_to "Log in", new_user_session_path %></li>
        <% end %>

</div>
<% if notice %>
<div class="alert alert-success"><%= notice %></div>
<% end %>
<% if alert %>
<div class="alert alert-warning"><%= alert %></div>
<% end %>



    <%= yield %>

    <nav class="navbar navbar-light fixed-bottom p-3" style="background-color: #740387;">
  <div class="container-fluid">
    <span class="text-white" style="font-size :20px; margin: auto;">
      Resotrack
    </span>
  </div>
</nav>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
<script
  src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>
  </body>
</html>